### PR TITLE
PHP8.4 Support Added

### PR DESCRIPTION
**Pull request by cod43156**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by acelaya** [comment]
How can we help pushing this forward?

@cod43156 could you rebase this branch and see if some of those issues get solved?

The documentation issues seem unrelated with this and complaining about preexisting files.

**Comment by froschdesign** [comment]
@acelaya 
> The documentation issues seem unrelated with this and complaining about preexisting files.

All problems must be resolved. This can also be done via a separate pull request.

**Comment by acelaya** [comment]
> @acelaya 
> > The documentation issues seem unrelated with this and complaining about preexisting files.
> 
> All problems must be resolved. This can also be done via a separate pull request.

I can probably take a look at the documentation linting issues, and then rebase this branch.

**Comment by acelaya** [comment]
Regarding the Autocloser job failure, it seems to be related with a missing token, so probably someone with admin permissions here would have to take a look.

**Comment by gsteel** [comment]
Thank you @cod43156 - this has been handled via #31

**Pull request closed without merging**
