### PR TITLE
Use lowercase `config` key to get configuration from container

### LINKED ISSUE #1: Use lowercase `config` key to get configuration from container
- [x] Is this related to quality assurance?
  

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-config/pull/66

### PR DESCRIPTION
**Pull request by michalbundyra**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Port of https://github.com/zendframework/zend-config/pull/66

Fixes #1

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
@michalbundyra Thank you, merged to master, forward port to develop.

**Comment by geerteltink** [comment]
Just wondering... isn't this a BC break for laminas?

AFAIK `$array['config'] !== $array['Config']`. This might break laminas components and projects based on this which expect the config key to be `Config`.

**Comment by samsonasik** [comment]
@geerteltink for laminas-mvc, there is alias for that https://github.com/laminas/laminas-mvc/blob/e3c420a96349f57655ed28b135290e331edb579c/src/Service/ServiceListenerFactory.php#L39-L41

**Comment by geerteltink** [comment]
Ah cool, I didn't know that.

**Pull request merged**
