### PR TITLE
Update psr/container to ^2.0

### PR DESCRIPTION
**Pull request by matjaz**

### CODE REVIEW

**Comment by Ocramius** [comment]
@matjaz please also update the lock file hash (`composer update nothing`) and check that CI is effectively downloading the new dependency when running with latest dependencies

**Comment by Ocramius** [comment]
According to CI, only `1.x` is being tested:

```
  - Installing psr/container (1.1.2
```

**Comment by Xerkus** [comment]
v2 in CI is prevented by dev dependencies via service manager

**Comment by froschdesign** [comment]
The current version of laminas-servicemanager does not support version 2 of psr/container.
The coming version 4 of laminas-servicemanager [will support this](https://github.com/laminas/laminas-servicemanager/blob/c902c4144e491d9cb2b3b652db3ac5cfc96abf42/composer.json#L31-L36).

**Comment by matjaz** [comment]
there are no breaking changes except PHP ver. https://github.com/php-fig/container/compare/1.1.2...2.0.2

**Comment by froschdesign** [comment]
@matjaz 
Please see: https://github.com/laminas/laminas-servicemanager/pull/175

**Comment by gsteel** [comment]
This library is being archived: https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2024-11-04-TSC-Minutes.md#archive--abandon-various-legacy-libraries

**Pull request closed without merging**
